apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - service.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: static-server
      namespace: static-server
    path: deployment.json
