apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: psa-serving-cert
  namespace: psa-system
spec:
  secretName: webhook-server-cert
  duration: 8760h0m0s # 1y
  issuerRef:
    kind: Issuer
    name: psa-selfsigned-issuer
  dnsNames:
    - psa-webhook-service
    - psa-webhook-service.psa-system
    - psa-webhook-service.psa-system.svc
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
