apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
  namespace: static-server
spec:
  template:
    spec:
      containers:
        - name: static-server
          image: quay.io/cybozu/training-troubleshooting:2.0.0
          imagePullPolicy: IfNotPresent
