apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server
  namespace: static-server
spec:
  template:
    spec:
      containers:
        - name: static-server
          resources:
            requests:
              memory: "1Mi"
              cpu: "50m"
            limits:
              memory: "20Mi"
              cpu: "50m"
