apiVersion: v1
kind: Namespace
metadata:
  name: wrk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrk
  labels:
    app.kubernetes.io/name: wrk
  namespace: wrk
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wrk
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wrk
    spec:
      containers:
      - name: wrk
        image: quay.io/cybozu/wrk:4.1.0
        imagePullPolicy: Never
        args:
          - "-d"
          - "24h"
          - "-c"
          - "100"
          - "http://static-server.static-server:8080/hoge.json"
