apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream.yaml
patchesStrategicMerge:
  - namespace.yaml
  - deployment.yaml
images:
  - name: quay.io/cybozu/cert-manager
    newTag: 1.3.1.1
